# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d304d7b7b2acffae798cd6e93385d48b8da83e57edcf9aeec53e7a28caaca229a06a583ac407df1c9078014de44b97df108e2725e12ec69aeb02f66b5bec63f6

test:
  secret_key_base: 70fef08b552286345f18ac7904dc337eb9c5764ae1f1401b9de06d2bfa582dfc3e774145dd5d75ffa3431e2bb58f86a97b00ac8fae1af1b1a26e3131a5778f41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 21f48b6c4bbb1c85aaba2e36a36d62af77d732ea5890b54485c10c9824311a135bf26b06abb89b11ba0ee6fe79d292ccbd2df566b2d8debdd291139944585904
